name: Deploy to Proxmox

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t resume-builder .

      - name: Stop existing container (if any)
        run: |
          docker stop resume-builder || true
          docker rm resume-builder || true

      - name: Run container
        run: |
          docker run -d \
            --name resume-builder \
            -p 3001:3000 \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            resume-builder